card/urls.py
from django.urls import path
from .views import CardListView, BoxView , CreateCardView , UpdateCardView, DeleteCardView

app_name = "card"

# define app's urls
urlpatterns = [
    path("", CardListView.as_view(), name="card-list"),
    path("box/<int:box_num>", BoxView.as_view(), name="box"),
    path("new", CreateCardView.as_view(), name="card-create"),
    path("update/<int:pk>", UpdateCardView.as_view(), name="card-update"),
    path("delete/<int:pk>", DeleteCardView.as_view(), name="card-delete"),
]

flashCard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("card.urls")),
]

card/models.py
from django.db import models

# Create your models here.
NUM_BOX = 5
BOXES = range(1, NUM_BOX  + 1) 

class Card(models.Model):
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)
    box = models.IntegerField(
        choices=zip(BOXES,BOXES),
    )
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.question
    

    def move(self, solved):
        new_box = self.box + 1 if solved else BOXES[0]

        if self.box in BOXES:
            self.box = new_box
            self.save()
            
        return self

card/views.py
import random
from typing import Any
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Card
from django.urls import reverse_lazy
from .form import CardCheckForm

# Create your views here.
class CardListView(ListView):
    model= Card
    queryset= Card.objects.all().order_by("box","-created_at")
    context_object_name = "card_list"


class BoxView(CardListView):
    template_name = "card/box.html"
    form_class = CardCheckForm


    def get_queryset(self):
        return Card.objects.filter(box=self.kwargs["box_num"])
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["box_number"] = self.kwargs["box_num"]

        if self.object_list:
            context["check_card"] = random.choice(self.object_list)
        return context
    
     
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = self.form_class(request.POST)
        if form.is_valid():
            card = get_object_or_404(Card, id=form.cleaned_data["card_id"])
            card.move(form.cleaned_data["solved"])
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    

class CreateCardView(SuccessMessageMixin, CreateView):
    model = Card
    fields = ["question", "answer", "box"]
    success_url = reverse_lazy("card:card-create")
    context_object_name = "card"

    success_message = "card add successfully"


class UpdateCardView(SuccessMessageMixin, UpdateView):
    model = Card
    fields = ["question", "answer", "box"]
    success_url = reverse_lazy("card:card-list")
    context_object_name = "card"
    success_message = "card update successfully"

class DeleteCardView(SuccessMessageMixin, DeleteView):
    model = Card
    context_object_name = "card"
    success_url = reverse_lazy("card:card-list")
    success_message = "card delete successfully"

    
                

card/templates/card/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  {% load static %}
  <head>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Flash Card</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'dist/css/root.css' %}" rel="stylesheet">
    <link href="{% static 'dist/css/navbars-offcanvas.css' %}" rel="stylesheet">
    <style>
    </style>
  </head>
  <body>

    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    <main>
      {% include "card/navigation.html" %}
      <div class="container my-5">
        {% if messages %}
        {% for message in messages %}
            <div id="alrt" class="text-center alert alert-{{ message.tags }}">
                {{ message|safe }}
            </div>
        {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
      </div>
      
    

    </main>
    <script src="{% static 'dist/js/bootstrap.bundle.min.js'%}"></script>
  </body>
</html>

card/templates/card/box.html
{% extends "card/base.html" %}
{% load humanize %}
{% block content %}
    <div class="bg-body-primary p-2 rounded text-center">
        <h3>{{box_number | ordinal}} Box</h3>
        <mark>{{object_list | length }}</mark> Card{{object_list | pluralize}} left in box
    </div>
    
    {% if  check_card%}
        {% with card=check_card %}
            {% include "card/card.html" %}
        {% endwith %}
    {% endif %}
{% endblock content %}

card/templates/card/box_links.html
{% load humanize %}
{% for box in boxes %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'card:box' box.box_number%}">
      {{box.box_number | ordinal}} Box <mark>{{box.card_count}}</mark></a>
  </li>
{% endfor %}

card/templates/card/card.html
<div class="bg-body-tertiary p-4 g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="modal-header border-bottom-0">
        <h4 class="modal-title fs-5">{{card.question}}</h4>
        <a href="{% url 'card:card-delete' card.id %}" class="btn-close" aria-label="Close"></a>
    </div>
    <div class="modal-body py-0">
        {% if not check_card %}
            <p>{{card.answer}}</p>
            <hr>
        {% else %}
            <details>
                <summary>Reveal Answer</summary>
                <p>{{card.answer}}</p>
            </details>
            <hr>
            {% include "card/card_check_form.html" with solved=True %}
            {% include "card/card_check_form.html" with solved=False %}
        {% endif %}
        <a href="{% url 'card:card-update' card.id%}">Edit</a>
    </div>
    
    
</div>

card/templates/card/card_check_form.html
<form class="mb-1" method="post">
    {% csrf_token %}
    <input type="hidden" name="card_id" value="{{card.id}}">
    <input type="hidden" name="solved" value="{{solved}}">
    {% if solved %}
        <input class="btn btn-outline-primary" type="submit" value="I Know">
    {% else %}
        <input class="btn btn-outline-secondary" type="submit" value="I don't Know">
    {% endif %}
</form>

card/templates/card/card_confirm_delete.html
{% extends "card/base.html" %}
{% block content %}
    <form class="form-signin w-100 m-auto" method="post">
            {% csrf_token %}
            <div class="modal-content rounded-3 shadow">
                <div class="modal-body p-4 text-center">
                  <h5 class="mb-0">Delete this card?</h5>
                  <p class="mb-0">{{object.question}}</p>
                </div>
                <div class="modal-footer flex-nowrap p-0">
                  <button type="submit"  class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end"><strong>Yes, delete</strong></button>
                  <a href="{{view.get_success_url}}" type="submit" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0">No thanks</a>
                </div>
              </div>
        </form>
{% endblock content %}

card/templates/card/card_form.html
{% extends "card/base.html" %}
{% load humanize %}
{% block content %}
  <div class="w-100 m-auto">
        <h1 class="h3 mb-3">
          {% if card %}
          Edit Card
          {% else %}
          Create New Card
          {% endif %}
          
        </h1>
        <form class="form-signin w-100 m-auto" method="post">
            {% csrf_token %}
            <div class="form-floating">
              <input class="form-control" type="text" name="question" maxlength="100" required="" id="id_question" value="{{card.question}}">
              <label for="id_question">Question:</label>    
            </div>

            <div class="form-floating">
                <input required="" type="text" name ="answer" class="form-control" id="id_answer" value="{{card.answer}}">
                <label for="id_answer">Answer</label>
            </div>

            <div class="form-floating">
              <select class="form-select" name="box" required="" id="id_box">
                {% for option in form.box %}
                  {{option}}
                {% endfor %}
              </select>
              <label for="id_box">Box:</label>
            <div> 
            <button class="btn btn-primary m-2" type="submit">Save Card</button>
        </form>
        <a class="btn btn-outline-secondary m-2" href="{% url "card:card-list" %}">cancel</a>
  </div>
{% endblock content %}

card/templates/card/card_list.html
{% extends "card/base.html" %}
{% load humanize %}
{% block content %}
    <div class="d-grid gap-2">
      <a class="btn btn-primary" type="link" href="{% url "card:card-create" %}">Add Card</a>
      <hr>
    </div>
    
    {% for card in card_list %}
        {% ifchanged %}
          <div class="m-4 text-center">
            <h3>{{card.box | ordinal}} Box</h3>
          </div>
        {% endifchanged%}
        {% include "card/card.html" %}
    {% endfor %}
    
{% endblock content %}

card/templates/card/navigation.html
{% load card_tags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Offcanvas navbar large">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url "card:card-list" %}">Flash Card</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbar2Label">Flash Card</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page"href="{% url "card:card-list" %}">All Cards</a>
            </li>
            {% boxes_as_links %}
          </ul>
        </div>
      </div>
    </div>
</nav>